# Instruct Travis to build PRs as well as merges
# to master. See https://stackoverflow.com/a/31882307/145400.
branches:
  only:
    - master

language: python

# Try to work around Travis' lack of Python support on OS X.
# https://github.com/travis-ci/travis-ci/issues/2312#issuecomment-289140791
matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: linux
      python: 3.6
    - os: linux
      python: pypy
    - os: linux
      python: pypy3
    - os: osx
      language: generic
      env: PYENV_VERSION=3.6.6
    - os: osx
      language: generic
      env: PYENV_VERSION=2.7.15


install:
  - source ./ci/env.sh
  - pip install .
  - pip install -r requirements-tests.txt


script:
    - python --version && uname -a

    - echo "Test with gevent 1.2.x"
    - pip install 'gevent>=1.2,<1.3' --upgrade
    - pip list
    - pytest -vv test/
    - bash examples/run-all.sh
    - bash audit.sh

    - echo "Test with gevent 1.3.x"
    - pip install 'gevent>=1.3' --upgrade
    - pip list
    - pytest -vv test/
    - bash examples/run-all.sh
    - bash audit.sh
